### PR TITLE
Added support of Alarm sound for Windows OS

### PR DESCRIPTION
**Pull request by AbhiPawar5**
Hi Syed Faizul Hai,
I really loved this package and thought to contribute!

Feature added : Added native sound alarm/beep of 5 seconds using winsound.

Please review it in your free time. Thanks! Take care!

### CODE REVIEW

**Comment by utkarshsethi** [comment]
I've added playing the alarm.wav file without the new library in #7

**Comment by AbhiPawar5** [comment]
Hi @faizulhai24 , @utkarshsethi has added some good changes for alarm. Please take a look! Thanks and Take care, guys.
EDIT : I guess I need to get latest changes from main, update this branch to main then create a PR?

**Comment by faizulhai24** [comment]
Sorry guys, did not receive the notifications for some reason, will check and merge the PR

**Comment by faizulhai24** [comment]
Thanks for the PR, Abhi.

**Comment by faizulhai24** [comment]
@utkarshsethi : I merged the PR's in FIFO. Hence you PR is now showing merge conflicts. I could resolve them, but I do not have a Windows PC to test it. So please resolve the conflicts and update the PR.

**Pull request merged**
